[project]
name = "data-source-json"
version = "0.1"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.entry-points."data_sources"]
# dsjson = "ovde uneti putanju do klase koja se koristi"
