[project]
name = "dscrypto"
version = "0.1"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.entry-points."data_sources"]
dscrypto = "data_source_crypto.data_source_crypto:CryptoDataSource"
