[project]
name = "simple_visualizer"
version = "0.1"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.entry-points."visualizers"]
block_visualizer = "simple_visualizer.simple_visualizer:SimpleVisualizer"
